context:
  version: "30.0.1"

package:
  name: create-jest
  version: ${{ version }}

source:
  url: https://registry.npmjs.org/create-jest/-/create-jest-${{ version }}.tgz
  sha256: eb860e7e465a6b74483a0cf6b595940d2d98fd21b392672ae2376ef48ae93105

build:
  number: 0
  noarch: generic

requirements:
  build:
    - nodejs
    - pnpm
    - pnpm-licenses
  run:
    - nodejs

tests:
  - script:
      - create-jest 2>&1 | grep -q 'Could not find a "package.json"'

about:
  license: MIT
  license_file:
    - LICENSE
    - third-party-licenses.txt
  summary: Create a new Jest project
  homepage: https://github.com/jestjs/jest
  repository: https://github.com/jestjs/jest

extra:
  recipe-maintainers:
    - danielnachun
