context:
  version: "30.0.2"

package:
  name: create-jest
  version: ${{ version }}

source:
  url: https://registry.npmjs.org/create-jest/-/create-jest-${{ version }}.tgz
  sha256: b43ad306de153e08f421960fd895da43b2d0dd56fc3b636ff04a6d0c53c5aa85

build:
  number: 0
  noarch: generic

requirements:
  build:
    - nodejs
    - pnpm
    - pnpm-licenses
  run:
    - nodejs

tests:
  - script:
      - create-jest 2>&1 | grep -q 'Could not find a "package.json"'

about:
  license: MIT
  license_file:
    - LICENSE
    - third-party-licenses.txt
  summary: Create a new Jest project
  homepage: https://github.com/jestjs/jest
  repository: https://github.com/jestjs/jest

extra:
  recipe-maintainers:
    - danielnachun
